name: ib-dev
channels:
  - conda-forge
  - openeye
dependencies:
  - python

  - openff-toolkit =0.14.3
  - openff-qcsubmit
  - openmmforcefields
  - smirnoff-plugins =2023.08.0

  - ipython
  - ipdb
  - pre-commit

  - openeye-toolkits
  - rich

  - pytest
  - pytest-cov
  - pytest-xdist
  - pytest-randomly

  - pip:
    - git+https://github.com/mattwthompson/de-forcefields.git@periodic-nonperiodic-methods
