name: yammbs-dev
channels:
  - openeye
  - conda-forge
dependencies:
  - python
  - pip
  - versioneer-518

  - openff-toolkit
  - openff-qcsubmit
  - openmmforcefields
  - smirnoff-plugins

  - geometric =1
  - pydantic =2

  # espaloma =0.3
  - de-forcefields ~=1.0.3
  - ipython
  - ipdb
  - pre-commit

  - openeye::openeye-toolkits
  - rich

  - pytest
  - pytest-cov
  - pytest-xdist
  - pytest-randomly
  - pytest-timeout
