name: ib-dev
channels:
  - openeye
  - conda-forge
dependencies:
  - python =3.10

  - openff-toolkit
  - openff-qcsubmit
  - openmmforcefields
  - smirnoff-plugins
  # espaloma =0.3
  - geometric =1
  - pydantic =2

  - ipython
  - ipdb
  - pre-commit

  - openeye::openeye-toolkits
  - rich

  - pytest
  - pytest-cov
  - pytest-xdist
  - pytest-randomly
  - pytest-timeout

  - pip:
    - git+https://github.com/mattwthompson/de-forcefields.git@periodic-nonperiodic-methods
