name: ib-dev
channels:
  - conda-forge
  - openeye
dependencies:
  - python

  # https://github.com/openforcefield/openff-qcsubmit/issues/230
  - openff-toolkit =0.14.0
  - openff-qcsubmit
  - openmmforcefields

  - ipython
  - ipdb
  - pre-commit

  - openeye-toolkits
  - rich

  - pytest
  - pytest-cov
  - pytest-xdist
  - pytest-randomly
