[build-system]
requires = [
    "setuptools",
    "versioningit",
]
build-backend = "setuptools.build_meta"

[project]
name = "yammbs"
version = "0.1.0"
readme = "README.md"

[tool.versioningit]

[tool.ruff]
line-length = 119

[tool.ruff.lint]
select = ["F", "E", "W", "NPY", "UP", "I"]

[project.scripts]
run_torsion_comparisons = "yammbs.scripts.run_torsion_comparisons:main"
