[build-system]
requires = [
    "setuptools",
    "versioningit",
]
build-backend = "setuptools.build_meta"

[project]
name = "yammbs"
version = "0.1.0"
readme = "README.md"

[tool.versioningit]

[tool.ruff]
line-length = 119
exclude = ["yammbs/_tests/**/*.py"]

[tool.ruff.lint]
preview = true
ignore = ["D105", "D107"]
select = ["D", "F", "E", "W", "NPY", "UP", "I", "RUF027"]

[project.scripts]
yammbs_analyse_torsions = "yammbs.scripts.run_torsion_comparisons:main"
