name: ib-dev
channels:
  - conda-forge
  - openeye
dependencies:
  - python =3.9
  - pip
  - qcfractal
  - qcengine =0.25
  - qcelemental =0.25
  - qcportal >=0.15
  - pint =0.20
  - openff-toolkit =0.11
  - openff-qcsubmit =0.4
  - openff-models

  - openmmforcefields =0.11.2
  - geometric <1

  - click

  - ipython
  - ipdb
  - pre-commit

  - openeye-toolkits

  - ipywidgets =7

  - seaborn
