name: ib-dev
channels:
  - conda-forge
  - openeye
dependencies:
  - python =3.9
  - pip
  - qcfractal =0.15.8.1
  - qcengine =0.24.1
  - qcelemental =0.25.0
  - qcportal
  - openff-qcsubmit
  - pint =0.19
  - openff-toolkit =0.10.6
  - openmmforcefields =0.11.2
  - geometric <1

  - ipython
  - ipdb

  - openeye-toolkits

  - ipywidgets =7

  - pip:
    - git+https://github.com/mattwthompson/openff-models
    - git+https://github.com/openforcefield/openff-qcsubmit@toolkit_011_support
    - git+https://github.com/MolSSI/QCEngine@master
