steps:
  - name: download_qcarchive
    collection_type: OptimizationResultCollection
#   data_set: "OpenFF Full Optimization Benchmark 1"
    data_set: "OpenFF Gen 2 Opt Set 3 Pfizer Discrepancy"
    cache_file: smaller.json
#   full-optimization-benchmark-1.json
    filter_smiles: ["NH+"]
  - name: filter_collection
    collection_type: OptimizationResultCollection
    file: smaller.json
#   file: 01-processed-qm.json
#   file: full-optimization-benchmark-1.json
    filtered_file: filtered.json
    filters:
      - invalid_cmiles
      # incomplete_record
      # connectivity_change
      # unambiguous_stereo
      # can_parametrize
        # this often fails b/c of conformer generation failures, maybe that could
        # be a separate filter check, also other possible failures with missing BCCs or AmberTools
        # convergences
        # this particular filter might also benefit from knowing which force field it's later going
        # to be used with
  - name: group_to_sdf
    collection_type: OptimizationResultCollection
    file: filtered.json
    sdf_file: 01-processed-qm.sdf
  - name: chunk_qm
    input_path: 01-processed-qm.sdf
    output_name: 01-processed-qm
    output_directory: 02-chunks/
    n_chunks: 8
  - name: minimize
    n_chunks: 8
    input_path: 02-chunks
    input_name: 01-processed-qm
    force_field_paths:
      - openff_unconstrained-1.0.0.offxml
      - openff_unconstrained-1.1.0.offxml
      - openff_unconstrained-1.2.0.offxml
      - openff_unconstrained-1.3.0.offxml
      - openff_unconstrained-2.0.0.offxml
      - openff_unconstrained-2.1.0.offxml
    force_field_type: SMIRNOFF
    output_directory: 02-outputs/
  - name: compute_metrics
    n_chunks: 8
    options: force-fields.json
    input_path: 02-outputs
    output_path: 03-metrics
  - name: plot
    input_path: 03-metrics/metrics.csv
