name: ci

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - name: Set up conda environment
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: devtools/conda-envs/dev.yaml

    - name: Install package
      run: |
        python -m pip install -e .

    - name: Run tests
      run: |
        pytest -r fEx -n logical --durations=10 \
          --cov=yammbs/ --cov-report=xml --cov-config=setup.cfg \
          yammbs/

    - name: CodeCov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
